apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ContainerDenyAddedCaps
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: containerdenyaddedcaps
spec:
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Pod
    - apiGroups:
      - apps
      kinds:
      - DaemonSet
      - Deployment
      - StatefulSet
